# Form implementation generated from reading ui file 'firstWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(153, 78)
        Dialog.setStyleSheet("QDialog {\n"
"background-color:black;\n"
"}")
        self.pb1 = QtWidgets.QPushButton(Dialog)
        self.pb1.setGeometry(QtCore.QRect(20, 10, 111, 28))
        self.pb1.setStyleSheet("@import url(\'https://fonts.googleapis.com/css2?family=Oswald:wght@300&display=swap\');\n"
"QPushButton {\n"
"font-family: \'Oswald\', sans-serif;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: green;\n"
"font-size: 20px;\n"
"}\n"
"")
        self.pb1.setObjectName("pb1")
        self.pb2 = QtWidgets.QPushButton(Dialog)
        self.pb2.setGeometry(QtCore.QRect(20, 40, 111, 28))
        self.pb2.setStyleSheet("@import url(\'https://fonts.googleapis.com/css2?family=Oswald:wght@300&display=swap\');\n"
"QPushButton {\n"
"font-family: \'Oswald\', sans-serif;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: red;\n"
"font-size: 20px;\n"
"}\n"
"")
        self.pb2.setObjectName("pb2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pb1.setText(_translate("Dialog", "Timer"))
        self.pb2.setText(_translate("Dialog", "Turn off"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
