# Form implementation generated from reading ui file 'firstWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_First(object):
    def setupUi(self, First):
        First.setObjectName("First")
        First.resize(153, 106)
        First.setStyleSheet("QDialog {\n"
"background-color:black;\n"
"}")
        self.pb1 = QtWidgets.QPushButton(First)
        self.pb1.setGeometry(QtCore.QRect(20, 10, 111, 28))
        self.pb1.setStyleSheet("@import url(\'https://fonts.googleapis.com/css2?family=Oswald:wght@300&display=swap\');\n"
"QPushButton{\n"
"border-radius:5px;\n"
"background-color:rgb(240, 240, 241)\n"
"}\n"
"QPushButton:hover {\n"
"background-color: green;\n"
"font-size: 20px;\n"
"}\n"
"")
        self.pb1.setObjectName("pb1")
        self.pb2 = QtWidgets.QPushButton(First)
        self.pb2.setGeometry(QtCore.QRect(20, 40, 111, 28))
        self.pb2.setStyleSheet("@import url(\'https://fonts.googleapis.com/css2?family=Oswald:wght@300&display=swap\');\n"
"QPushButton{\n"
"border-radius:5px;\n"
"background-color:rgb(240, 240, 241)\n"
"}\n"
"QPushButton:hover {\n"
"background-color: red;\n"
"font-size: 20px;\n"
"}\n"
"")
        self.pb2.setObjectName("pb2")
        self.pb2_2 = QtWidgets.QPushButton(First)
        self.pb2_2.setGeometry(QtCore.QRect(20, 70, 111, 28))
        self.pb2_2.setStyleSheet("QPushButton{\n"
"border-radius:5px;\n"
"background-color:rgb(240, 240, 241)\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(0, 255, 255);\n"
"font-size: 20px\n"
"}\n"
"")
        self.pb2_2.setObjectName("pb2_2")

        self.retranslateUi(First)
        QtCore.QMetaObject.connectSlotsByName(First)

    def retranslateUi(self, First):
        _translate = QtCore.QCoreApplication.translate
        First.setWindowTitle(_translate("First", "TTW"))
        self.pb1.setText(_translate("First", "Timer"))
        self.pb2.setText(_translate("First", "Turn off"))
        self.pb2_2.setText(_translate("First", "Weather"))


