# Form implementation generated from reading ui file 'timerWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Timer(object):
    def setupUi(self, Timer):
        Timer.setObjectName("Timer")
        Timer.resize(213, 137)
        Timer.setStyleSheet("QDialog {\n"
"background-color:black;\n"
"}")
        self.timeEdit = QtWidgets.QTimeEdit(Timer)
        self.timeEdit.setGeometry(QtCore.QRect(50, 40, 118, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.dateEdit = QtWidgets.QDateEdit(Timer)
        self.dateEdit.setGeometry(QtCore.QRect(60, 70, 101, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.pushButton = QtWidgets.QPushButton(Timer)
        self.pushButton.setGeometry(QtCore.QRect(10, 100, 93, 28))
        self.pushButton.setStyleSheet("QPushButton:hover {\n"
"background-color:rgb(0, 255, 255);\n"
"font-size: 20px\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Timer)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 100, 93, 28))
        self.pushButton_2.setStyleSheet("QPushButton:hover {\n"
"background-color:rgb(0, 255, 255);\n"
"font-size: 20px\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Timer)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 191, 22))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"\n"
"}")
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Timer)
        QtCore.QMetaObject.connectSlotsByName(Timer)

    def retranslateUi(self, Timer):
        _translate = QtCore.QCoreApplication.translate
        Timer.setWindowTitle(_translate("Timer", "Dialog"))
        self.pushButton.setText(_translate("Timer", "Done"))
        self.pushButton_2.setText(_translate("Timer", "Back"))
        self.lineEdit.setText(_translate("Timer", "    What u want to see here ?"))



