# Form implementation generated from reading ui file 'timerWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Timer(object):
    def setupUi(self, Timer):
        Timer.setObjectName("Timer")
        Timer.resize(211, 110)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("clock.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Timer.setWindowIcon(icon)
        Timer.setStyleSheet("QDialog {\n"
"background-color:black;\n"
"}")
        self.pushButton = QtWidgets.QPushButton(Timer)
        self.pushButton.setGeometry(QtCore.QRect(10, 70, 93, 28))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-radius:5px;\n"
"background-color:rgb(240, 240, 241)\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(0, 244, 138);\n"
"font-size: 20px\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Timer)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 70, 93, 28))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border-radius:5px;\n"
"background-color:rgb(240, 240, 241)\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(0, 255, 255);\n"
"font-size: 20px\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Timer)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 191, 22))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"border-radius:5px;\n"
"background-color:rgb(240, 240, 241)\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Timer)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 40, 151, 22))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"border-radius:5px;\n"
"background-color:rgb(240, 240, 241)\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Timer)
        QtCore.QMetaObject.connectSlotsByName(Timer)

    def retranslateUi(self, Timer):
        _translate = QtCore.QCoreApplication.translate
        Timer.setWindowTitle(_translate("Timer", "Timer"))
        self.pushButton.setText(_translate("Timer", "Done"))
        self.pushButton_2.setText(_translate("Timer", "Back"))
        self.lineEdit.setText(_translate("Timer", "    What u want to see here ?"))
        self.lineEdit_2.setText(_translate("Timer", " write amount of minutes"))



