# Form implementation generated from reading ui file 'weather.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_weather(object):
    def setupUi(self, weather):
        weather.setObjectName("weather")
        weather.resize(212, 138)
        font = QtGui.QFont()
        font.setPointSize(10)
        weather.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("clock.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        weather.setWindowIcon(icon)
        weather.setStyleSheet("QDialog {\n"
"background:black;\n"
"}")
        self.but1 = QtWidgets.QPushButton(weather)
        self.but1.setGeometry(QtCore.QRect(10, 100, 93, 28))
        self.but1.setStyleSheet("QPushButton{\n"
"border-radius:5px;\n"
"background-color:rgb(240, 240, 241)\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(0, 244, 138);\n"
"font-size: 20px\n"
"}\n"
"")
        self.but1.setObjectName("but1")
        self.but2 = QtWidgets.QPushButton(weather)
        self.but2.setGeometry(QtCore.QRect(110, 100, 93, 28))
        self.but2.setStyleSheet("QPushButton{\n"
"border-radius:5px;\n"
"background-color:rgb(240, 240, 241)\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(0, 255, 255);\n"
"font-size: 20px\n"
"}\n"
"")
        self.but2.setObjectName("but2")
        self.lineEdit = QtWidgets.QLineEdit(weather)
        self.lineEdit.setGeometry(QtCore.QRect(40, 5, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"border-radius:5px;\n"
"background-color:rgb(240, 240, 241)\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.weatherexport = QtWidgets.QTextBrowser(weather)
        self.weatherexport.setGeometry(QtCore.QRect(10, 30, 191, 61))
        self.weatherexport.setStyleSheet("QTextBrowser{\n"
"border-radius:5px;\n"
"background-color:rgb(240, 240, 241)\n"
"}")
        self.weatherexport.setObjectName("weatherexport")

        self.retranslateUi(weather)
        QtCore.QMetaObject.connectSlotsByName(weather)

    def retranslateUi(self, weather):
        _translate = QtCore.QCoreApplication.translate
        weather.setWindowTitle(_translate("weather", "Weather"))
        self.but1.setText(_translate("weather", "Done"))
        self.but2.setText(_translate("weather", "Back"))
        self.lineEdit.setText(_translate("weather", " Country or City"))
        self.weatherexport.setHtml(_translate("weather", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))



